//! Domain types for LaReview application
//! Defines the core data structures and business objects used throughout the application.

use serde::{Deserialize, Serialize};

/// Unique identifier for a pull request
pub type PullRequestId = String;

/// Unique identifier for a review task
pub type TaskId = String;

/// Risk level associated with a review task, indicating the potential impact of the changes
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "UPPERCASE")]
pub enum RiskLevel {
    /// Low risk changes with minimal impact
    #[default]
    Low,
    /// Medium risk changes that require attention
    Medium,
    /// High risk changes that require careful review
    High,
}

/// A pull request to be reviewed
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PullRequest {
    /// Unique identifier for the pull request
    pub id: PullRequestId,
    /// Title of the pull request
    pub title: String,
    /// Optional description of the pull request
    pub description: Option<String>,
    /// Repository name in "owner/repo" format
    pub repo: String,
    /// Author of the pull request
    pub author: String,
    /// Branch name of the pull request
    pub branch: String,
    /// Creation timestamp in RFC3339 format
    pub created_at: String,
}

/// Statistics for a review task
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct TaskStats {
    /// Number of lines added in the changes
    pub additions: u32,
    /// Number of lines deleted in the changes
    pub deletions: u32,
    /// Risk level of the changes
    pub risk: RiskLevel,
    /// Tags describing the nature of the changes
    #[serde(default)]
    pub tags: Vec<String>,
}

/// Status of a review task
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "UPPERCASE")]
pub enum TaskStatus {
    /// Task has not been started yet
    #[default]
    #[serde(alias = "PENDING")]
    Pending,
    /// Task is currently being worked on
    #[serde(alias = "INPROGRESS")]
    #[serde(alias = "IN_PROGRESS")]
    #[serde(alias = "inprogress")]
    #[serde(alias = "in_progress")]
    InProgress,
    /// Task has been completed
    #[serde(alias = "REVIEWED")]
    #[serde(alias = "COMPLETED")]
    Done,
    /// Task has been reviewed but was determined to be ignorable
    #[serde(alias = "IGNORED")]
    Ignored,
}

/// A review task spanning one or more files
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReviewTask {
    /// Unique identifier for the task
    pub id: TaskId,
    /// ID of the pull request this task belongs to
    pub pr_id: PullRequestId,
    /// Title of the review task
    pub title: String,
    /// Detailed description of the review task
    pub description: String,
    /// List of files affected by this task
    pub files: Vec<String>,
    /// Statistical information about the changes
    pub stats: TaskStats,
    /// Diff strings showing the specific changes to review
    #[serde(default)]
    pub diffs: Vec<String>,
    /// AI-generated insight about the task (optional)
    pub insight: Option<String>,
    /// Optional diagram describing the task context
    pub diagram: Option<String>,
    /// Flag indicating if the task was generated by AI
    #[serde(default)]
    pub ai_generated: bool,
    /// Current review status of the task
    #[serde(default)]
    pub status: TaskStatus,
    /// Optional sub-flow name this task belongs to for organizational purposes
    #[serde(default)]
    pub sub_flow: Option<String>,
}

/// Status of a plan entry
#[allow(dead_code)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum PlanStatus {
    /// Plan entry has not been started yet
    #[default]
    #[serde(alias = "PENDING")]
    Pending,
    /// Plan entry is currently in progress
    #[serde(alias = "INPROGRESS")]
    #[serde(alias = "IN_PROGRESS")]
    #[serde(alias = "inprogress")]
    #[serde(alias = "in_progress")]
    InProgress,
    /// Plan entry has been completed
    #[serde(alias = "COMPLETED")]
    Completed,
}

/// Priority level of a plan entry
#[allow(dead_code)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum PlanPriority {
    /// Low priority plan entry
    #[serde(alias = "LOW")]
    Low,
    /// Medium priority plan entry
    #[default]
    #[serde(alias = "MEDIUM")]
    Medium,
    /// High priority plan entry
    #[serde(alias = "HIGH")]
    High,
}

/// A single entry in a plan
#[allow(dead_code)]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanEntry {
    /// Content/narrative description of the plan entry
    pub content: String,
    /// Priority level of the plan entry
    #[serde(default)]
    pub priority: PlanPriority,
    /// Current status of the plan entry
    #[serde(default)]
    pub status: PlanStatus,
    /// Optional metadata associated with the plan entry
    #[serde(default)]
    pub meta: Option<serde_json::Value>,
}

/// A plan containing multiple entries
#[allow(dead_code)]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Plan {
    /// List of plan entries
    pub entries: Vec<PlanEntry>,
    /// Optional metadata associated with the plan
    #[serde(default)]
    pub meta: Option<serde_json::Value>,
}

/// Review note stored per task
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Note {
    /// ID of the task this note belongs to
    pub task_id: TaskId,
    /// Content of the note
    pub body: String,
    /// Timestamp when the note was last updated
    pub updated_at: String,
    /// Optional file path for line-specific comments
    #[serde(default)]
    pub file_path: Option<String>,
    /// Optional line number for line-specific comments
    #[serde(default)]
    pub line_number: Option<u32>,
}
